import type { Metadata } from "next";
import { Montserrat, Space_Grotesk, Raleway } from "next/font/google";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Providers } from "@/redux/provider";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  weight: ["400", "500", "600", "700"],
});

const raleWay = Raleway({
  subsets: ["latin"],
  variable: "--font-raleWay",
  weight: ["400", "500", "600", "700"],
});

const grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-grotesk",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "FEHT Health",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${raleWay.variable} ${grotesk.variable}  ${montserrat.variable}`}
        style={{ maxWidth: "2000px" }}
      >
        <ToastContainer />

        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
